spring:
  application:
    name: tlias-wen-management
    #mysql连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  helper-dialect: mysql
logging: 
  level: 
    org.springframework.jdbc.support.JdbcTransactionManager: debug

file:
  upload-dir: /Users/tongweiya/Desktop/images/


